version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "8083:5432"
    environment:
      - POSTGRES_USER=user_group
      - POSTGRES_PASSWORD=user_group
      - POSTGRES_DB=user_group
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: