version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "8083:5432"
    environment:
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=users
      - POSTGRES_DB=users
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: